apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: stock-analyzer
  namespace: stock-analyzer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stocks-analyzer
  namespace: stock-analyzer
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
      - configmaps
  - verbs:
      - '*'
    apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stocks-role-binding
  namespace: stock-analyzer
subjects:
  - kind: ServiceAccount
    name: stocks-analyzer
    namespace: stock-analyzer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stocks-analyzer
